apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: swifty17/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: swifty17/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # - image: swifty17/event-bus
    #   context: event-bus
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: swifty17/moderation
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: swifty17/posts
    #   context: posts
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: swifty17/query
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .




# apiVersion: skaffold/v4beta3
# kind: Config
# manifests:
#   rawYaml:
#     - ./infra/k8s/*
# build:
#   # local:
#   #   push: false
#   googleCloudBuild:
#     projectId: ticketing-dev-420413  
#   artifacts:
#     - image: us.gcr.io/ticketing-dev-420413/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: "src/**/*.ts"
#             dest: .